### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yucc2018** [DCASE-REPO/bulbul_bird_detection_dcase2018#1]
```root@e1a8c6f8a61a:~# /dfsdata/yucc1_data/bulbul_bird_detection_dcase2018/run.sh stage1_prepare
Running sub-task stage1_prepare:
Preparing file lists.
NOT computing file lists for test sets since no test sets were specified yet.
Computing spectrograms.
Making /dfsdata/yucc1_data/dcaset3/workingfiles/spect/BirdVox-DCASE-20k/00053d90-e4b9-4045-a2f1-f39efc90cfa9.wav.h5
Traceback (most recent call last):
  File "/dfsdata/yucc1_data/bulbul_bird_detection_dcase2018/code/extract_melspect.py", line 390, in <module>
    main()
  File "/dfsdata/yucc1_data/bulbul_bird_detection_dcase2018/code/extract_melspect.py", line 353, in main
    preserve_energy=options.preserve_energy)
  File "/dfsdata/yucc1_data/bulbul_bird_detection_dcase2018/code/extract_melspect.py", line 314, in extract_melspect
    samples = read_ffmpeg(infile, sample_rate, downmix, cmd='ffmpeg')
  File "/dfsdata/yucc1_data/bulbul_bird_detection_dcase2018/code/extract_melspect.py", line 145, in read_ffmpeg
    num_channels = get_num_channels(infile, cmd[:2]+'probe') or 1
  File "/dfsdata/yucc1_data/bulbul_bird_detection_dcase2018/code/extract_melspect.py", line 133, in get_num_channels
    info = subprocess.check_output([cmd, "-v", "quiet", "-show_streams", infile])
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Failed making /dfsdata/yucc1_data/dcaset3/workingfiles/spect/BirdVox-DCASE-20k/00053d90-e4b9-4045-a2f1-f39efc90cfa9.wav.h5 - exiting
Done computing spectrograms.
```

when i run the run.sh,  I got this error and could not found how to fix this. Could anyone help me?

**Comment by danstowell** [comment]
Does folder `/dfsdata/yucc1_data/dcaset3/workingfiles` exist? If you create it does that solve the problem?

**Comment by yucc2018** [comment]
@danstowell  yes, I am sure that folder exist. I ceated it before run the script run.sh.

**Comment by yucc2018** [comment]
@danstowell Folder /dfsdata/yucc1_data/dcaset3/workingfiles exists. However, that error is still there.

**Comment by yucc2018** [comment]
I got the answer of the question. In my ubuntu system, I didn't install ffmpeg and h5py packages.  When I install this two packages, The error is missing.

**Comment by danstowell** [comment]
Thanks
