### ISSUE TITLE
Stage1 preprocess not working

### ISSUE THREAD

**Issue by stefanknegt** [DCASE-REPO/bulbul_bird_detection_dcase2018#6]
I am running into a problem with the preprocess script. I get the following error after updating the config file and renaming the data (where XYZ is a location on my machine). I have checked this exact path and it is correct. So it seems to be the case that the script cannot make the .h5 file, while this location is writeable. I also tried running it with sudo.

Do you have any idea what I am doing wrong? Thanks a lot!

`Traceback (most recent call last):
  File ".././code/extract_melspect.py", line 390, in <module>
    main()
  File ".././code/extract_melspect.py", line 353, in main
    preserve_energy=options.preserve_energy)
  File ".././code/extract_melspect.py", line 314, in extract_melspect
    samples = read_ffmpeg(infile, sample_rate, downmix, cmd='ffmpeg')
  File ".././code/extract_melspect.py", line 145, in read_ffmpeg
    num_channels = get_num_channels(infile, cmd[:2]+'probe') or 1
  File ".././code/extract_melspect.py", line 133, in get_num_channels
    info = subprocess.check_output([cmd, "-v", "quiet", "-show_streams", infile])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Failed making /XYZ/bulbul_bird_detection_dcase2018-badch2018/workingfiles/spect/BirdVox-DCASE-20k/00053d90-e4b9-4045-a2f1-f39efc90cfa9.wav.h5 - exiting`

**Comment by danstowell** [comment]
I don't know. But perhaps it's because you don't have `ffmpeg` command installed on your machine, or perhaps python does not know where exactly to find it.

Looks like you're on Mac. I use Ubuntu (and so did the original author) so I don't know how to make sure python can execute ffmpeg, but you should check that.

As described in the readme, there's a branch "portable_submission'" which does not use ffmpeg.

**Comment by stefanknegt** [comment]
The version on the portable_submission branch works fine, thanks!
